name: GitHub Metrics

on:
  schedule: # Runs daily
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual run

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          username: souravbiswas19
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta
